accumulate_grad_batches: 16
add_base_flow: false
backbone_checkpoint_path: null
backbone_size: small
batch_size: 2
bce_pos_weight: 40.0
checkpoint_path: null
confidence_threshold: 0
crop_height: 1040
early_stopping_patience: 3
error_as_eval_loss: true
experiment_description: null
experiment_name: Type_No_Weather_Figlib_all_fires
focal_alpha: 0.25
focal_gamma: 2
freeze_backbone: false
gradient_clip_val: 0
image_loss_only: false
image_pos_weight: 5.0
is_background_removal: false
is_debug: false
is_extra_training: false
is_maskrcnn: false
is_object_detection: false
is_test_only: false
labels_path: /root/drive_clone_numpy
learning_rate: 0.001
load_images_from_split: true
mask_omit_images: false
max_epochs: 1
metadata_path: ./data/metadata.pkl
min_epochs: 1
model_type_list:
- RawToTile_ResNet
- TileToTile_LSTM
- TileToTileImage_SpatialViT
no_blur_augment: true
no_brightness_contrast_augment: true
no_color_augment: true
no_early_stopping: false
no_flip_augment: true
no_intermediate_supervision: true
no_pre_tile: true
no_pretrain_backbone: true
no_resize_crop_augment: true
no_sixteen_bit: true
no_stochastic_weight_avg: true
num_tile_samples: 0
num_workers: 4
omit_list: null
optical_flow_path: null
optimizer_type: SGD
optimizer_weight_decay: 0.001
original_height: 1536
original_width: 2048
pretrain_epochs: null
raw_data_path: /root/raw_images
resize_height: 1392
resize_width: 1856
series_length: 2
smoke_threshold: 250
test_split_path: ./data/final_split/test_images_final.txt
test_split_size: 0.15
tile_embedding_size: 1000
tile_loss_type: bce
tile_overlap: 20
tile_size: 224
time_range_max: 2400
time_range_min: -2400
train_split_path: ./data/final_split/train_images_final.txt
train_split_size: 0.7
use_image_preds: true
use_lr_schedule: false
val_split_path: ./data/final_split/val_images_final.txt
